[package]
name = "eden"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["boot"]

[dependencies]
bootloader = "0.10.13"
uart_16550 = "0.2.11"
x86_64 = "0.14.10"

[package.metadata.bootloader]
framebuffer-address = "0xFFFFFFFFB0000000"
kernel-stack-size = "0x20000" # 128KB
kernel-stack-address = "0xFFFFFFFFFF000000"
boot-info-address = "0xFFFFFFFFFFFFF000" # Last 4KB
dynamic-range-start = "0xFFFF800000000000"