[package]
name = "eden"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["boot"]

[dependencies]
bootloader = "0.10.13"
spin = "0.9.4"
lazy_static = { version = "1.4.0", features = ["spin_no_std"]}
x86_64 = "0.14.10"
uart_16550 = "0.2.11"

[package.metadata.bootloader]
